services:
  db:
    image: postgres:17
    container_name: lu_db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: lu_migrations
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      sh -c "
      until nc -z db 5432; do
        echo 'waiting for database...';
        sleep 2;
      done;
      echo 'Executing migrations';
      migrate -path=/migrations -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable up
        "

  api:
    build: .
    container_name: lu_api
    env_file:
      - .env
    depends_on:
      migrate:
        condition:
          service_completed_successfully
    ports:
      - "${API_PORT}:${API_PORT}"
volumes:
  postgres_data:
