services:
  db:
    image: postgres:17
    container_name: lu_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: lu_api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${API_PORT}:${API_PORT}"
volumes:
  postgres_data:
